server:
  port: 8080

spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    liquibase-schema: public
    default-schema: public

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: public
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379